# 
# TODO add {}_git_info.json for each dependency repo (other repos do this in their Dockerfile).
# TODO have remote vs local be parameterized in config file rather than requiring switching comment blocks here.
# 

ARG NGEN_BASE_IMAGE="ghcr.io/ngwpc/ngen:latest"
FROM $NGEN_BASE_IMAGE

### Additional user args, these have to be after the FROM
ARG REPO_TAG__REGION_MGR

### Static args
ARG PYTHON_ENV="/ngen-app/ngen-python/bin"
ARG GITHUB_ORG_URL="https://github.com/NGWPC"
ARG GITHUBUSERCONTENT_ORG_URL="https://raw.githubusercontent.com/NGWPC"
ARG REPO_NAME__REGION_MGR="nwm-region-mgr"

### For Python 3.10 base image (ngen ghcr ngen:latest as of 10/28/25)
# ARG PYTHON_VERSION_STR="python3.10"
### For Python 3.11 base image (ngen development as of 10/28/25)
ARG PYTHON_VERSION_STR="python3.11"

### Activate the venv
ENV PATH="${PYTHON_ENV}:${PATH}"
RUN pip install --upgrade pip


### Regionalization python scripts and sample config files

#From GitHub
RUN mkdir -p "/ngen-app/${REPO_NAME__REGION_MGR}/configs/"
RUN curl -L https://raw.githubusercontent.com/NGWPC/${REPO_NAME__REGION_MGR}/${REPO_TAG__REGION_MGR}/run_ngen_vpu_docker.py \
    -o /ngen-app/${REPO_NAME__REGION_MGR}/run_ngen_vpu_docker.py
RUN curl -L https://raw.githubusercontent.com/NGWPC/${REPO_NAME__REGION_MGR}/${REPO_TAG__REGION_MGR}/configs/config_ngen.yaml \
    -o /ngen-app/${REPO_NAME__REGION_MGR}/configs/config_ngen.yaml
    
# From local
#COPY run_ngen_vpu_docker.py /ngen-app/${REPO_NAME__REGION_MGR}/run_ngen_vpu_docker.py
#COPY configs/config_ngen.yaml /ngen-app/${REPO_NAME__REGION_MGR}/configs/config_ngen.yaml

