FROM python:3.11-slim

### User args, these have to be after the FROM
ARG REPO_TAG__REGION_MGR="development"

### Static args
ARG PYTHON_ENV="/ngen-app/ngen-python/bin"
ARG GITHUB_ORG_URL="https://github.com/NGWPC"
ARG GITHUBUSERCONTENT_ORG_URL="https://raw.githubusercontent.com/NGWPC"
ARG REPO_NAME__REGION_MGR="nwm-region-mgr"
ARG PYTHON_VERSION_STR="python3.11"
ARG PKG_NAME="nwm_region_mgr"

### Activate the venv
ENV PATH="${PYTHON_ENV}:${PATH}"
RUN pip install --upgrade pip

# Install git and build-essential
RUN apt-get update && apt-get install -y git build-essential && rm -rf /var/lib/apt/lists/*

# Install curl (used to download files from GitHub)
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*


##############################
#### nwm-region-mgr setup ####

## From GitHub
RUN set -eux; \
    mkdir -p "/ngen-app/${REPO_NAME__REGION_MGR}/configs"; \
    BASE_URL="${GITHUBUSERCONTENT_ORG_URL}/${REPO_NAME__REGION_MGR}/${REPO_TAG__REGION_MGR}"; \
    curl -L "$BASE_URL/regionalization.py" \
        -o "/ngen-app/${REPO_NAME__REGION_MGR}/regionalization.py"; \
    for f in config_general.yaml config_formreg.yaml config_parreg.yaml; do \
        curl -L "$BASE_URL/configs/$f" \
            -o "/ngen-app/${REPO_NAME__REGION_MGR}/configs/$f"; \
    done

RUN pip install "${PKG_NAME}[parreg] @ git+${GITHUB_ORG_URL}/${REPO_NAME__REGION_MGR}@${REPO_TAG__REGION_MGR}"

## From local (copy required files only)
# COPY ${PKG_NAME}/ "/ngen-app/${REPO_NAME__REGION_MGR}/${PKG_NAME}/"
# COPY pyproject.toml "/ngen-app/${REPO_NAME__REGION_MGR}/pyproject.toml"
# COPY regionalization.py "/ngen-app/${REPO_NAME__REGION_MGR}/regionalization.py"
# COPY configs/config_general.yaml "/ngen-app/${REPO_NAME__REGION_MGR}/configs/config_general.yaml"
# COPY configs/config_formreg.yaml "/ngen-app/${REPO_NAME__REGION_MGR}/configs/config_formreg.yaml"
# COPY configs/config_parreg.yaml "/ngen-app/${REPO_NAME__REGION_MGR}/configs/config_parreg.yaml"

# RUN pip install ${PKG_NAME}[parreg] "/ngen-app/${REPO_NAME__REGION_MGR}"
