
general:
  vpu: vpu09
  run_name: test3
  algorithm: hdbscan
  start_time: '2022-10-01T00:00:00'
  end_time: '2022-10-01T10:00:00'
  nprocs: "2"
  base_dir: /ngen-app/nwm-region-mgr/data
  par_file: '{base_dir}/outputs/{run_name}/params/formulation_params_{algorithm}_conus_{vpu}.csv'
  pair_file: '{base_dir}/outputs/{run_name}/pairs/pairs_{algorithm}_conus_{vpu}_mswm.csv'
  gpkg_file: '{base_dir}/inputs/hydrofabric/gpkg_vpu/vpu_09_patch.gpkg'
  config_template: /ngen-app/nwm-region-mgr/sample_files/configs/mswm.config.template.docker
  log_file: '{base_dir}/region_{algorithm}_{vpu}.log'
  log_level: INFO
